@extends('template')

@section('content')
<style>
  table thead {
    position: sticky;
    top: 0;
  }

  table tbody tr td:first-child {
    position: sticky;
    left: 0;
    background-color: #39ADB4;
    color: white;
    font-weight: bold;
    text-align: center;
  }

  .table-responsive {
    max-height: calc(100vh - 280px);;
    overflow: auto;
  }
</style>
<div class="templatemo-content-widget no-padding">
    <div class="panel panel-default table-responsive">
        <table class="table table-striped table-bordered templatemo-user-table">
            <thead>
                <tr>
                    <th>OVR</th>
                    <th>GOL</th>
                    <th>LE LD ADE ADD</th>
                    <th>ZAG</th>
                    <th>VOL</th>
                    <th>MC</th>
                    <th>PE PD MEI ME MD</th>
                    <th>ATA SA MAE MAD</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                  <td>92</td>
                  <td>44M</td>
                  <td>62.5M</td>
                  <td>64.5M</td>
                  <td>66M</td>
                  <td>76M</td>
                  <td>78M</td>
                  <td>80M</td>
                </tr>
                <tr>
                  <td>91</td>
                  <td>39M</td>
                  <td>55M</td>
                  <td>57M</td>
                  <td>58M</td>
                  <td>67M</td>
                  <td>69M</td>
                  <td>71M</td>
                </tr>
                <tr>
                  <td>90</td>
                  <td>34M</td>
                  <td>48M</td>
                  <td>49.5M</td>
                  <td>50.5M</td>
                  <td>58M</td>
                  <td>60M</td>
                  <td>61.5M</td>
                </tr>
                <tr>
                  <td>89</td>
                  <td>29M</td>
                  <td>41.5M</td>
                  <td>42.5M</td>
                  <td>43.5M</td>
                  <td>50.5M</td>
                  <td>51.5M</td>
                  <td>53M</td>
                </tr>
                <tr>
                  <td>88</td>
                  <td>26M</td>
                  <td>37M</td>
                  <td>38M</td>
                  <td>39M</td>
                  <td>45M</td>
                  <td>46M</td>
                  <td>47M</td>
                </tr>
                <tr>
                  <td>87</td>
                  <td>22M</td>
                  <td>31.5M</td>
                  <td>32.5M</td>
                  <td>33M</td>
                  <td>38M</td>
                  <td>39M</td>
                  <td>40M</td>
                </tr>
                <tr>
                  <td>86</td>
                  <td>19.5M</td>
                  <td>27.5M</td>
                  <td>28.5M</td>
                  <td>29M</td>
                  <td>33.5M</td>
                  <td>34.5M</td>
                  <td>35.5M</td>
                </tr>
                <tr>
                  <td>85</td>
                  <td>17M</td>
                  <td>24M</td>
                  <td>24.5M</td>
                  <td>25M</td>
                  <td>29M</td>
                  <td>30M</td>
                  <td>30.5M</td>
                </tr>
                <tr>
                  <td>84</td>
                  <td>13.5M</td>
                  <td>19.5M</td>
                  <td>20M</td>
                  <td>20.5M</td>
                  <td>23.5M</td>
                  <td>24M</td>
                  <td>25M</td>
                </tr>
                <tr>
                  <td>83</td>
                  <td>11.5M</td>
                  <td>16M</td>
                  <td>16.5M</td>
                  <td>17M</td>
                  <td>19.5M</td>
                  <td>20M</td>
                  <td>20.5M</td>
                </tr>
                <tr>
                  <td>82</td>
                  <td>9.5M</td>
                  <td>14M</td>
                  <td>14M</td>
                  <td>14.5M</td>
                  <td>17M</td>
                  <td>17M</td>
                  <td>17.5M</td>
                </tr>
                <tr>
                  <td>81</td>
                  <td>8M</td>
                  <td>11M</td>
                  <td>11.5M</td>
                  <td>11.5M</td>
                  <td>13.5M</td>
                  <td>14M</td>
                  <td>14M</td>
                </tr>
                <tr>
                  <td>80</td>
                  <td>6.5M</td>
                  <td>9M</td>
                  <td>9.5M</td>
                  <td>9.5M</td>
                  <td>11M</td>
                  <td>11.5M</td>
                  <td>12M</td>
                </tr>
                <tr>
                  <td>79</td>
                  <td>5.5M</td>
                  <td>8M</td>
                  <td>8M</td>
                  <td>8M</td>
                  <td>9.5M</td>
                  <td>10M</td>
                  <td>10M</td>
                </tr>
                <tr>
                  <td>78</td>
                  <td>4.5M</td>
                  <td>6.5M</td>
                  <td>6.5M</td>
                  <td>7M</td>
                  <td>8M</td>
                  <td>8M</td>
                  <td>8.5M</td>
                </tr>
                <tr>
                  <td>77</td>
                  <td>3.9M</td>
                  <td>5.5M</td>
                  <td>5.5M</td>
                  <td>6M</td>
                  <td>6.5M</td>
                  <td>7M</td>
                  <td>7M</td>
                </tr>
                <tr>
                  <td>76</td>
                  <td>3.4M</td>
                  <td>4.8M</td>
                  <td>4.9M</td>
                  <td>5M</td>
                  <td>6M</td>
                  <td>6M</td>
                  <td>6M</td>
                </tr>
                <tr>
                  <td>75</td>
                  <td>2.9M</td>
                  <td>4.1M</td>
                  <td>4.3M</td>
                  <td>4.4M</td>
                  <td>5M</td>
                  <td>5M</td>
                  <td>5.5M</td>
                </tr>
                <tr>
                  <td>74</td>
                  <td>2.5M</td>
                  <td>3.5M</td>
                  <td>3.6M</td>
                  <td>3.7M</td>
                  <td>4.3M</td>
                  <td>4.4M</td>
                  <td>4.5M</td>
                </tr>
                <tr>
                  <td>73</td>
                  <td>1.8M</td>
                  <td>2.5M</td>
                  <td>2.6M</td>
                  <td>2.6M</td>
                  <td>3M</td>
                  <td>3.1M</td>
                  <td>3.2M</td>
                </tr>
                <tr>
                  <td>72</td>
                  <td>1.4M</td>
                  <td>1.9M</td>
                  <td>2M</td>
                  <td>2M</td>
                  <td>2.4M</td>
                  <td>2.4M</td>
                  <td>2.5M</td>
                </tr>
                <tr>
                  <td>71</td>
                  <td>1M</td>
                  <td>1.5M</td>
                  <td>1.5M</td>
                  <td>1.6M</td>
                  <td>1.8M</td>
                  <td>1.8M</td>
                  <td>1.9M</td>
                </tr>
                <tr>
                  <td>70</td>
                  <td>775M</td>
                  <td>1.1M</td>
                  <td>1.1M</td>
                  <td>1.2M</td>
                  <td>1.3M</td>
                  <td>1.4M</td>
                  <td>1.4M</td>
                </tr>
                <tr>
                  <td>69</td>
                  <td>450K</td>
                  <td>650K</td>
                  <td>675K</td>
                  <td>700K</td>
                  <td>800K</td>
                  <td>825K</td>
                  <td>850K</td>
                </tr>
                <tr>
                  <td>68</td>
                  <td>400K</td>
                  <td>550K</td>
                  <td>575K</td>
                  <td>575K</td>
                  <td>675K</td>
                  <td>700K</td>
                  <td>725K</td>
                </tr>
                <tr>
                  <td>67</td>
                  <td>325K</td>
                  <td>475K</td>
                  <td>500K</td>
                  <td>505K</td>
                  <td>575K</td>
                  <td>600K</td>
                  <td>600K</td>
                </tr>
                <tr>
                  <td>66</td>
                  <td>280K</td>
                  <td>400K</td>
                  <td>425K</td>
                  <td>425K</td>
                  <td>475K</td>
                  <td>500K</td>
                  <td>525K</td>
                </tr>
                <tr>
                  <td>65</td>
                  <td>240K</td>
                  <td>325K</td>
                  <td>350K</td>
                  <td>350K</td>
                  <td>400K</td>
                  <td>425K</td>
                  <td>425K</td>
                </tr>
                <tr>
                  <td>64</td>
                  <td>200K</td>
                  <td>280K</td>
                  <td>290K</td>
                  <td>300K</td>
                  <td>350K</td>
                  <td>350K</td>
                  <td>350K</td>
                </tr>
                <tr>
                  <td>63</td>
                  <td>160K</td>
                  <td>230K</td>
                  <td>240K</td>
                  <td>240K</td>
                  <td>280K</td>
                  <td>290K</td>
                  <td>290K</td>
                </tr>
                <tr>
                  <td>62</td>
                  <td>130K</td>
                  <td>190K</td>
                  <td>190K</td>
                  <td>200K</td>
                  <td>230K</td>
                  <td>240K</td>
                  <td>240K</td>
                </tr>
                <tr>
                  <td>61</td>
                  <td>110K</td>
                  <td>160K</td>
                  <td>160K</td>
                  <td>160K</td>
                  <td>190K</td>
                  <td>200K</td>
                  <td>200K</td>
                </tr>
                <tr>
                  <td>60</td>
                  <td>90K</td>
                  <td>130K</td>
                  <td>130K</td>
                  <td>140K</td>
                  <td>160K</td>
                  <td>160K</td>
                  <td>170K</td>
                </tr>
                <tr>
                  <td>59</td>
                  <td>70K</td>
                  <td>100K</td>
                  <td>100K</td>
                  <td>100K</td>
                  <td>120K</td>
                  <td>120K</td>
                  <td>120K</td>
                </tr>
                <tr>
                  <td>58</td>
                  <td>60K</td>
                  <td>80K</td>
                  <td>80K</td>
                  <td>80K</td>
                  <td>100K</td>
                  <td>100K</td>
                  <td>100K</td>
                </tr>
                <tr>
                  <td>57</td>
                  <td>50K</td>
                  <td>60K</td>
                  <td>70K</td>
                  <td>70K</td>
                  <td>80K</td>
                  <td>80K</td>
                  <td>80K</td>
                </tr>
                <tr>
                  <td>56</td>
                  <td>40K</td>
                  <td>60K</td>
                  <td>60K</td>
                  <td>60K</td>
                  <td>70K</td>
                  <td>70K</td>
                  <td>70K</td>
                </tr>
                <tr>
                  <td>55</td>
                  <td>40K</td>
                  <td>50K</td>
                  <td>50K</td>
                  <td>50K</td>
                  <td>60K</td>
                  <td>60K</td>
                  <td>60K</td>
                </tr>
                <tr>
                  <td>54</td>
                  <td>30K</td>
                  <td>40K</td>
                  <td>40K</td>
                  <td>40K</td>
                  <td>50K</td>
                  <td>50K</td>
                  <td>50K</td>
                </tr>
                <tr>
                  <td>53</td>
                  <td>30K</td>
                  <td>40K</td>
                  <td>40K</td>
                  <td>40K</td>
                  <td>40K</td>
                  <td>50K</td>
                  <td>50K</td>
                </tr>
                <tr>
                  <td>52</td>
                  <td>20K</td>
                  <td>30K</td>
                  <td>30K</td>
                  <td>30K</td>
                  <td>40K</td>
                  <td>40K</td>
                  <td>40K</td>
                </tr>
                <tr>
                  <td>51</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>30K</td>
                  <td>30K</td>
                  <td>30K</td>
                </tr>
                <tr>
                  <td>51<</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>20K</td>
                  <td>20K</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection